version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms
    ports: ["3306:3306"]
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: lms
      SPRING_DATASOURCE_PASSWORD: lms
      JWT_SECRET: TXlTdXBlclNlY3JldEtleUZvckp3dFNpZ25pbmcxMjM0NTY3ODkwIQ==
      JWT_EXPIRATION: "3600000"
    ports: ["8080:8080"]
